title: Isaac Lee Zais
email: isaaczais@hotmail.com
description: >-
  This is a personal website for Isaac Lee Zais.
  It is for showing my career path, education, and interesting personal projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://isaaczais.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "images"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
